version: 2
updates:
- package-ecosystem: nuget
  directory: "/src"
  schedule:
    interval: daily
  open-pull-requests-limit: 1000
  groups:
    AWSSDK:
      patterns:
        - "AWSSDK.*"
    NServiceBusCore:
      patterns:
        - "NServiceBus"
        - "NServiceBus.AcceptanceTesting"
        - "NServiceBus.AcceptanceTests.Sources"
        - "NServiceBus.PersistenceTests.Sources"
        - "NServiceBus.TransportTests.Sources"
  ignore:
    # Particular.Analyzers updates are distributed via RepoStandards
    - dependency-name: "Particular.Analyzers"
    # Changing these 3 dependencies affects the .NET SDK and Visual Studio versions we support 
    # These types of updates should be more intentional than an automated update
    - dependency-name: "Microsoft.Build.Utilities.Core"
    - dependency-name: "Microsoft.CodeAnalysis.CSharp"
    - dependency-name: "Microsoft.CodeAnalysis.CSharp.Workspaces"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 1000
